import type { Metadata } from "next";
import { Nova_Round } from "next/font/google";
import "./globals.css";

const nova = Nova_Round({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body className={nova.className}>{children}</body>
    </html>
  );
}
